M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date ti 30. huhtikuuta 2024 07.39.17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-30T07:39:17+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
%
G90
G05
T1
X115.0Y-188.78
X115.0Y-195.58
M30
